
[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/peterhellberg/flip"

[[constraint]]
  branch = "master"
  name = "github.com/peterhellberg/giphy"

[[constraint]]
  branch = "master"
  name = "github.com/peterhellberg/hi"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
